colunas = [
    "Id",
    "Razao Social",
    "Descrição",
    "Número do item",
    "Grupo",
    "Status da Ferramenta",
    "Número de série",
    "Número da Requisição",
    "Referência Organizacional",
    "Tipo de Contrato",
    "Data de Início do Contrato",
    "Data de Término do Contrato",
    "Duração do contrato",
    "Ferramenta de empréstimo permitida",
    "Cobertura de roubo",
    "Mensalidade",
    "Último Reparo",
    "Custo de Reparo",
    "Quantidade de reparos",
    "Garantia",
    "Data de compra",
    "Fim do período sem custo",
    "Número do Equipamento",
    "Geração"
]